#!/usr/bin/env python3
"""
Template Combiner - Sistema de Combinación Modular
Combina paletas de colores, fuentes y layouts para generar templates CSS únicos
"""

import os
import random
from pathlib import Path
from typing import Dict, List, Tuple

from color_palette_generator import ColorPaletteGenerator
from font_family_generator import FontFamilyGenerator
from layout_css_generator import LayoutCSSGenerator


class TemplateCombiner:
    """Combina módulos CSS independientes en templates únicos"""
    
    def __init__(self):
        """Inicializa los generadores"""
        self.color_gen = ColorPaletteGenerator()
        self.font_gen = FontFamilyGenerator()
        self.layout_gen = LayoutCSSGenerator()
        
        self.combinaciones_generadas = set()
    
    def generar_combinacion_unica(self, 
                                  palette_index: int = None,
                                  font_index: int = None,
                                  layout_index: int = None) -> Dict[str, any]:
        """
        Genera una combinación única de palette + font + layout
        
        Args:
            palette_index: Índice de paleta (None = aleatorio)
            font_index: Índice de fuente (None = aleatorio)
            layout_index: Índice de layout (None = aleatorio)
            
        Returns:
            dict: Combinación completa
        """
        # Si no se especifican índices, elegir aleatoriamente
        if palette_index is None:
            palette_index = random.randint(0, len(self.color_gen.PALETAS) - 1)
        if font_index is None:
            font_index = random.randint(0, len(self.font_gen.FONT_COMBINATIONS) - 1)
        if layout_index is None:
            layout_index = random.randint(0, len(self.layout_gen.LAYOUTS) - 1)
        
        # Obtener componentes
        palette = self.color_gen.obtener_paleta(palette_index)
        font = self.font_gen.obtener_combinacion(font_index)
        layout = self.layout_gen.obtener_layout(layout_index)
        
        # Crear identificador único
        combo_id = f"{palette_index}_{font_index}_{layout_index}"
        
        return {
            "id": combo_id,
            "palette_index": palette_index,
            "font_index": font_index,
            "layout_index": layout_index,
            "palette": palette,
            "font": font,
            "layout": layout,
            "nombre": f"{palette['nombre']}_{font['nombre']}_{layout['nombre']}"
        }
    
    def generar_css_combinado(self, combinacion: Dict[str, any]) -> str:
        """
        Genera CSS completo combinando todos los módulos
        
        Args:
            combinacion: Diccionario con la combinación
            
        Returns:
            str: CSS completo combinado
        """
        css = f"""/*
 * Template ID: {combinacion['id']}
 * Palette: {combinacion['palette']['nombre']} ({combinacion['palette']['descripcion']})
 * Fonts: {combinacion['font']['nombre']} ({combinacion['font']['descripcion']})
 * Layout: {combinacion['layout']['nombre']} ({combinacion['layout']['descripcion']})
 * Generated by Template Combiner
 */

"""
        
        # 1. Imports de fuentes
        css += "/* ===== FONT IMPORTS ===== */\n"
        css += self.font_gen.generar_css_imports(combinacion['font'])
        css += "\n"
        
        # 2. Variables CSS (colores + fuentes)
        css += "/* ===== CSS VARIABLES ===== */\n"
        css += ":root {\n"
        
        # Variables de color
        css += f"    /* Palette: {combinacion['palette']['nombre']} */\n"
        css += f"    --primary-color: {combinacion['palette']['primary']};\n"
        css += f"    --secondary-color: {combinacion['palette']['secondary']};\n"
        css += f"    --accent-color: {combinacion['palette']['accent']};\n"
        css += f"    --background-color: {combinacion['palette']['background']};\n"
        css += f"    --text-color: {combinacion['palette']['text']};\n"
        css += f"    --light-text: {combinacion['palette']['light_text']};\n"
        css += f"    --card-bg: {combinacion['palette']['card_bg']};\n"
        css += "\n"
        
        # Variables de fuente
        css += f"    /* Fonts: {combinacion['font']['nombre']} */\n"
        css += f"    --font-primary: {combinacion['font']['primary']};\n"
        css += f"    --font-secondary: {combinacion['font']['secondary']};\n"
        css += f"    --line-height: {combinacion['font']['line_height']};\n"
        css += f"    --heading-weight: {combinacion['font']['heading_weight']};\n"
        css += f"    --body-weight: {combinacion['font']['body_weight']};\n"
        css += "}\n\n"
        
        # 3. Reset y estilos base
        css += self._get_base_styles()
        
        # 4. Layout estructural
        css += "/* ===== LAYOUT STRUCTURE ===== */\n"
        css += self.layout_gen.generar_css_layout(combinacion['layout'])
        css += "\n"
        
        # 5. Componentes comunes
        css += self._get_common_components()
        
        return css
    
    def _get_base_styles(self) -> str:
        """Genera estilos base comunes"""
        return """/* ===== BASE STYLES ===== */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: var(--font-secondary);
    font-weight: var(--body-weight);
    line-height: var(--line-height);
    color: var(--text-color);
    background-color: var(--background-color);
}

h1, h2, h3, h4, h5, h6 {
    font-family: var(--font-primary);
    font-weight: var(--heading-weight);
    line-height: 1.2;
    color: var(--primary-color);
}

h1 { font-size: 2.5em; }
h2 { font-size: 2em; }
h3 { font-size: 1.5em; }
h4 { font-size: 1.2em; }

a {
    color: var(--primary-color);
    text-decoration: none;
    transition: color 0.3s;
}

a:hover {
    color: var(--secondary-color);
}

img {
    max-width: 100%;
    height: auto;
    display: block;
}

"""
    
    def _get_common_components(self) -> str:
        """Genera componentes comunes (header, nav, footer, etc.)"""
        return """/* ===== COMMON COMPONENTS ===== */

/* Navigation */
.nav {
    display: flex;
    gap: 20px;
    align-items: center;
}

.nav-link {
    padding: 10px 15px;
    font-family: var(--font-primary);
    font-weight: 600;
    color: var(--text-color);
    transition: all 0.3s;
}

.nav-link:hover {
    color: var(--secondary-color);
    background: rgba(0,0,0,0.05);
    border-radius: 5px;
}

/* Logo */
.logo {
    font-family: var(--font-primary);
    font-weight: var(--heading-weight);
    color: var(--primary-color);
}

.tagline {
    font-family: var(--font-secondary);
    color: var(--light-text);
    font-size: 0.9em;
}

/* Featured Section */
.featured-section {
    margin: 40px 0;
}

.featured-article {
    position: relative;
    overflow: hidden;
    border-radius: 10px;
}

/* Article Meta */
.article-meta, .card-meta {
    display: flex;
    gap: 15px;
    font-size: 0.85em;
    color: var(--light-text);
    margin-top: 10px;
}

/* Category Badge */
.category, .card-category, .card-category-badge {
    display: inline-block;
    padding: 5px 12px;
    background: var(--accent-color);
    color: white;
    font-size: 0.75em;
    font-weight: 700;
    text-transform: uppercase;
    border-radius: 3px;
    margin-bottom: 10px;
}

/* Sidebar Widgets */
.widget {
    background: var(--card-bg);
    padding: 20px;
    border-radius: 8px;
    margin-bottom: 20px;
}

.widget-title {
    font-size: 1.2em;
    margin-bottom: 15px;
    padding-bottom: 10px;
    border-bottom: 2px solid var(--primary-color);
}

/* Footer */
.footer {
    background: var(--primary-color);
    color: white;
    padding: 40px 0;
    margin-top: 60px;
}

.footer a {
    color: white;
}

/* Buttons */
.btn, .btn-subscribe {
    padding: 10px 20px;
    background: var(--primary-color);
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    font-family: var(--font-primary);
    font-weight: 600;
    transition: all 0.3s;
}

.btn:hover, .btn-subscribe:hover {
    background: var(--secondary-color);
    transform: translateY(-2px);
}

/* Search Input */
.search-input {
    padding: 10px 15px;
    border: 1px solid rgba(0,0,0,0.2);
    border-radius: 5px;
    font-family: var(--font-secondary);
}

/* Utility Classes */
.text-center { text-align: center; }
.mb-20 { margin-bottom: 20px; }
.mt-20 { margin-top: 20px; }

"""
    
    def generar_template_css(self, 
                            template_number: int,
                            output_dir: str,
                            palette_index: int = None,
                            font_index: int = None,
                            layout_index: int = None):
        """
        Genera un archivo CSS de template numerado
        
        Args:
            template_number: Número del template
            output_dir: Directorio de salida
            palette_index: Índice de paleta (None = aleatorio)
            font_index: Índice de fuente (None = aleatorio)
            layout_index: Índice de layout (None = aleatorio)
        """
        # Generar combinación
        combinacion = self.generar_combinacion_unica(palette_index, font_index, layout_index)
        
        # Generar CSS
        css = self.generar_css_combinado(combinacion)
        
        # Guardar archivo
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        filename = f"template{template_number}.css"
        output_path = f"{output_dir}/{filename}"
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(css)
        
        # Guardar metadata
        metadata = {
            "template_number": template_number,
            "combination_id": combinacion['id'],
            "palette": combinacion['palette']['nombre'],
            "font": combinacion['font']['nombre'],
            "layout": combinacion['layout']['nombre']
        }
        
        return metadata
    
    def generar_multiples_templates(self, 
                                   num_templates: int,
                                   output_dir: str,
                                   aleatorio: bool = True) -> List[Dict]:
        """
        Genera múltiples templates únicos
        
        Args:
            num_templates: Cantidad de templates a generar
            output_dir: Directorio de salida
            aleatorio: Si True, combinaciones aleatorias; si False, secuencial
            
        Returns:
            list: Lista de metadatos de templates generados
        """
        metadatos = []
        
        # Calcular combinaciones totales posibles
        total_palettes = len(self.color_gen.PALETAS)
        total_fonts = len(self.font_gen.FONT_COMBINATIONS)
        total_layouts = len(self.layout_gen.LAYOUTS)
        total_combinations = total_palettes * total_fonts * total_layouts
        
        print(f"📊 Combinaciones posibles: {total_combinations:,}")
        print(f"   {total_palettes} paletas × {total_fonts} fuentes × {total_layouts} layouts\n")
        
        if aleatorio:
            print(f"🎲 Generando {num_templates} templates aleatorios...\n")
            for i in range(1, num_templates + 1):
                metadata = self.generar_template_css(i, output_dir)
                metadatos.append(metadata)
                print(f"✅ Template {i}: {metadata['palette']} + {metadata['font']} + {metadata['layout']}")
        else:
            print(f"🔢 Generando {num_templates} templates secuenciales...\n")
            combo_idx = 0
            for i in range(1, num_templates + 1):
                # Calcular índices secuenciales
                palette_idx = (combo_idx // (total_fonts * total_layouts)) % total_palettes
                font_idx = (combo_idx // total_layouts) % total_fonts
                layout_idx = combo_idx % total_layouts
                
                metadata = self.generar_template_css(i, output_dir, palette_idx, font_idx, layout_idx)
                metadatos.append(metadata)
                print(f"✅ Template {i}: {metadata['palette']} + {metadata['font']} + {metadata['layout']}")
                
                combo_idx += 1
        
        return metadatos
    
    def calcular_posibilidades(self) -> Dict[str, int]:
        """
        Calcula el número total de combinaciones posibles
        
        Returns:
            dict: Información sobre posibilidades
        """
        num_palettes = len(self.color_gen.PALETAS)
        num_fonts = len(self.font_gen.FONT_COMBINATIONS)
        num_layouts = len(self.layout_gen.LAYOUTS)
        total = num_palettes * num_fonts * num_layouts
        
        return {
            "palettes": num_palettes,
            "fonts": num_fonts,
            "layouts": num_layouts,
            "total_combinations": total
        }


def main():
    """Función principal"""
    print("🎨 Template Combiner - Sistema Modular CSS")
    print("=" * 70)
    
    combiner = TemplateCombiner()
    
    # Mostrar posibilidades
    stats = combiner.calcular_posibilidades()
    print(f"\n📊 Estadísticas del Sistema:")
    print(f"   Paletas de colores: {stats['palettes']}")
    print(f"   Combinaciones de fuentes: {stats['fonts']}")
    print(f"   Layouts estructurales: {stats['layouts']}")
    print(f"   ───────────────────────────────")
    print(f"   Total combinaciones únicas: {stats['total_combinations']:,}")
    
    # Ejemplo de combinación
    print(f"\n🔍 Ejemplo de Combinación:\n")
    combo = combiner.generar_combinacion_unica(0, 0, 0)
    print(f"ID: {combo['id']}")
    print(f"Paleta: {combo['palette']['nombre']} - {combo['palette']['descripcion']}")
    print(f"Fuente: {combo['font']['nombre']} - {combo['font']['descripcion']}")
    print(f"Layout: {combo['layout']['nombre']} - {combo['layout']['descripcion']}")
    
    # Generar templates de ejemplo
    output_dir = "../templates/css"
    num_templates = 100
    
    print(f"\n💾 ¿Generar {num_templates} templates en {output_dir}? (s/n): ", end="")
    response = input().lower()
    
    if response == 's':
        print()
        metadatos = combiner.generar_multiples_templates(num_templates, output_dir, aleatorio=True)
        
        # Guardar metadatos
        import json
        metadata_file = f"{output_dir}/templates_metadata.json"
        with open(metadata_file, 'w', encoding='utf-8') as f:
            json.dump(metadatos, f, indent=2, ensure_ascii=False)
        
        print(f"\n✅ Se generaron {len(metadatos)} templates")
        print(f"📂 Ubicación: {output_dir}/")
        print(f"📄 Metadatos: {metadata_file}")
    else:
        print("\n❌ Generación cancelada")


if __name__ == "__main__":
    main()
